/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module top (
  input IO1,
  input IO2,
  input IO3,
  input IO4,
  output QO2,
  output QO3,
  output QO4,
  output QO1,
  output QO5
);
  assign QO1 = (IO1 | (~ IO4 & ~ (IO2 | IO3)));
  assign QO5 = (IO3 | IO4);
  assign QO2 = IO2;
  assign QO3 = IO3;
  assign QO4 = IO4;
endmodule
